### ISSUE TITLE
Enlace css y js

### ISSUE THREAD

**Issue by luisbello30** [alexjchn/PensumMaker#1]
Hola, hola 
Tienes un enlace a <link rel="stylesheet" href="Estilos/chosen.css">
no se si te falta este archivo...

También tienes haces referencia a <script type="text/javascript" src="Scripts/main.js"></script>
y no existe tal carpeta .

Saludos, espero la actualización =)

**Comment by alexjchn** [comment]
Gracias!, se me paso corregir eso.
